# All units in km seconds and degrees. M0 in rad, elements for epoch J2000.0
epoch: 2000-01-01T00:00:00Z
star:
  name: Sun
  μ: 132712440018
  radius: 696340
  atmosphere_height: 0
  siderial_day: 2192832
planets:
  - name: Mercury
    μ: 22031.86855
    radius: 2439.7
    atmosphere_height: 0
    siderial_day: 5067031
    orbit:
      a: 57909068
      e: 0.20563593
      i: 7.00498
      Ω: 48.33077
      ω: 29.12703
      M0: 3.05143
  - name: Venus
    μ: 324858.592
    radius: 6051.8
    atmosphere_height: 250
    siderial_day: -20996760
    orbit:
      a: 108208000
      e: 0.00677672
      i: 3.39468
      Ω: 76.67984
      ω: 54.92262
      M0: 0.87814
  - name: Earth
    μ: 398600.435507
    radius: 6378.137
    atmosphere_height: 100
    siderial_day: 86164
    orbit:
      a: 149598023
      e: 0.0167086
      i: 0.00005
      Ω: -11.26064
      ω: 114.20783
      M0: 6.25428
  - name: Mars
    μ: 42828.375816
    radius: 3396.2
    atmosphere_height: 125
    siderial_day: 88642
    orbit:
      a: 227939200
      e: 0.09339410
      i: 1.84969
      Ω: 49.55954
      ω: 286.50283
      M0: 0.33861
  - name: Jupiter
    μ: 126712764.1
    radius: 71492
    atmosphere_height: 5000
    siderial_day: 35730
    orbit:
      a: 778570000
      e: 0.04838624
      i: 1.30440
      Ω: 100.47391
      ω: 274.41357
      M0: 0.34357
  - name: Saturn
    μ: 37940584.8418
    radius: 60268
    atmosphere_height: 6000
    siderial_day: 38340
    orbit:
      a: 1433530000
      e: 0.05386179
      i: 2.48599
      Ω: 113.66242
      ω: 339.392
      M0: 5.53956
  - name: Uranus
    μ: 5794556.4
    radius: 25559
    atmosphere_height: 2500
    siderial_day: -62064
    orbit:
      a: 2872460000
      e: 0.04725744
      i: 0.77264
      Ω: 74.01693
      ω: 96.93735
      M0: 2.48430
  - name: Neptune
    μ: 6836527.10058
    radius: 24764
    atmosphere_height: 2500
    siderial_day: 57996
    orbit:
      a: 4504440000
      e: 0.00859048
      i: 1.77004
      Ω: 131.78423
      ω: 276.33610
      M0: 4.53416
  - name: Pluto
    μ: 870.3
    radius: 1188.3
    atmosphere_height: 0
    siderial_day: -551856
    orbit:
      a: 5906376272
      e: 0.24880766
      i: 17.14175
      Ω: 110.30347
      ω: 113.76329
      M0: 0.25352
